CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  organization TEXT,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL
);
