apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whisp-ingress
  namespace: ${GKE_NAMESPACE}
  labels:
    app: whisp-ingress
    env: ${ENVIRONMENT}
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: ${GKE_LB_STATIC_IP_NAME}
spec:
  tls:
  - hosts:
    - ${INGRESS_HOST}
    secretName: whisp-ingress-tls
  rules:
  - host: ${INGRESS_HOST}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: whisp-api
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whisp-app
            port:
              number: 80
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: whisp-api
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whisp-app
            port:
              number: 80
