# .github/workflows/test.yml
name: Run Tests

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 18

      - run: npm ci
      - run: npm run test
